spring:
  application:
    name: expense-tracker-cli
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/expenses_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update